### ISSUE TITLE
Footer logos should have padding around them

### ISSUE THREAD

**Issue by benjamincoleman** [notbinary/website#21]
<img width="624" alt="Screen Shot 2019-04-26 at 17 39 50" src="https://user-images.githubusercontent.com/64877/56822893-6271bb00-684a-11e9-9039-c7e145f24ad4.png">

Padding should be around the image itself, rather than being part of the image.

**Comment by BenDarby** [comment]
I've set the `background-position: 95% 95%;` to create some padding
