### ISSUE TITLE
Card content min-height

### ISSUE THREAD

**Issue by benjamincoleman** [notbinary/website#22]
Card content of varying heights exposes the yellow background of the card. 

<img width="1256" alt="Screen Shot 2019-04-26 at 18 41 17" src="https://user-images.githubusercontent.com/64877/56826046-0495a100-6853-11e9-8081-e35fb6c930e8.png">

More issues on this piece in the blog template when we have actual content: 

<img width="1287" alt="Screen Shot 2019-05-01 at 16 28 31" src="https://user-images.githubusercontent.com/64877/57025156-4ac17a80-6c2e-11e9-85ad-0160089b2568.png">

**Comment by BenDarby** [comment]
Just needed the background-colour setting to white on the card element, all good now.
